name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # TODO: Add 'Validate Gradle wrapper'
      # - name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_MAVEN_URL: ${{ secrets.ORG_GRADLE_PROJECT_MAVEN_URL }}
          ORG_GRADLE_PROJECT_MAVEN_USER: ${{ secrets.ORG_GRADLE_PROJECT_MAVEN_USER }}
          ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAVEN_PASSWORD }}
        run: ./gradlew build
